### ISSUE TITLE
Autenticar Professor

### ISSUE THREAD

**Issue by ViniciusSD** [pedrovinchi1/Oficina2#4]
Esta funcionalidade vai fazer a autentificação do professor no sistema.

**Comment by pedrovinchi1** [comment]
9fd9682cd6938ba023615a14ea132d0ab0cd10c1 / 5a792b3b97a6b11d18711bae51a24472f059bf01 / d2778a4e24423cce38f146cb761fa0eb164e4c81 / bc607e2e90d2bcf5e3ff4a97f1dc18b82b344933 /
